
fancy_responses = {
	'WH_Questions': {'fancy_name': 'question words', 'examples': 'such as how, why and where?'},
	'Bare_Command': {'fancy_name': 'soft commands', 'examples': 'such as consider'},
	'Conjunction_Start': {'fancy_name': 'conjunctions at the beginning of the sentence', 'examples': 'such as but, and, then'},
	'Affirmation': {'fancy_name': 'affirmative words', 'examples': 'such as for you'},
	'For_You': {'fancy_name': 'phrases that shows consideration to the other person', 'examples': 'such as for you...'},
	'Swearing': {'fancy_name': 'swear words', 'examples': ''},
	'Formal_Title': {'fancy_name': 'be more formal', 'examples': 'by using formal titles'},
	'For_Me': {'fancy_name': 'phrases that show nuanced opinions', 'examples': 'such as for me...'},
	'Informal_Title': {'fancy_name': 'informal titles', 'examples': 'by using informal titles such as dude, buddy'},
	'Agreement': {'fancy_name': 'agreement phrases', 'examples': 'such as I agree and you are right'},
	'Disagreement': {'fancy_name': 'disagreement phrases', 'examples': 'such as I disagree or You are wrong'},
	'Give_Agency': {'fancy_name': 'giving phrases', 'examples': 'such as let you or you may'},
	'Could_You': {'fancy_name': 'ask formally', 'examples': 'such as could you or would you'},
	'Gratitude': {'fancy_name': 'gratitude', 'examples': 'such as thanks'},
	'Positive_Emotion': {'fancy_name': 'positive emotions', 'examples': 'such as adore or happy'},
	'Reasoning': {'fancy_name': 'reasoning words', 'examples': 'such as because or explain'},
	'Subjectivity': {'fancy_name': 'subjective phrases', 'examples': 'such as I believe or In my opinion'},
	'Acknowledgement': {'fancy_name': 'acknowledgement phrases', 'examples': 'such as I understand or I get'},
	'Negative_Emotion': {'fancy_name': 'negative emotions', 'examples': 'such as absurd or ignorant'},
	'Negation': {'fancy_name': 'fewer negation words', 'examples': 'such as did not or will not'},
	'Hedges': {'fancy_name': 'hedging words', 'examples': 'such as almost or maybe'},
	'Impersonal_Pronoun': {'fancy_name': 'impersonal pronouns', 'examples': 'such as others or someone'},
	'Filler_Pause': {'fancy_name': 'filler pauses', 'examples': 'such as um and hm'},
	'By_The_Way': {'fancy_name': 'the phrase by the way', 'examples': ''},
	'Reassurance': {'fancy_name': 'reassuring words', 'examples': 'such as it\'s ok or don\'t worry'},
	'Hello': {'fancy_name': 'greeting phrases', 'examples': 'such as hello or hi'},
	'Please': {'fancy_name': 'polite requests', 'examples': 'such as please'},
	'First_Person_Plural': {'fancy_name': 'first person phrases', 'examples': 'such as us and our'},
	'First_Person_Single': {'fancy_name': 'first person phrases', 'examples': 'such as myself or I'},
	'Second_Person': {'fancy_name': 'second person phrases', 'examples': 'such as you or yourself'},
	'Apology': {'fancy_name': 'apologetic tones', 'examples': 'such as excuse me or forgive me'},
	'Truth_Intensifier': {'fancy_name': 'words that intensify a statement', 'examples': 'such as really or surely'},
	'Can_You': {'fancy_name': 'ask formally', 'examples': 'such as can you or will you'},
	'Let_Me_Know': {'fancy_name': 'the phrase let me know', 'examples': ''},
	'Goodbye': {'fancy_name': 'farewell phrases', 'examples': 'such as goodbye or see you later'},
	'Ask_Agency': {'fancy_name': 'ask agencies', 'examples': 'such as do me a favour or might I'},
	'YesNo_Questions': {'fancy_name': 'yes or no questions', 'examples': 'as opposed to who, where, what, and why questions'},
	'Adverb_Limiter': {'fancy_name': 'words that limit a statement', 'examples': 'such as just or only'},
	}